// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Driving.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/Drive.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Driving::Driving() : Subsystem("Driving") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    backRightDrive = RobotMap::drivingBackRightDrive;
    backLeftDrive = RobotMap::drivingBackLeftDrive;
    frontRightDrive = RobotMap::drivingFrontRightDrive;
    frontLeftDrive = RobotMap::drivingFrontLeftDrive;
    robotDrive41 = RobotMap::drivingRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Driving::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new Drive(0, 0));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Driving::driveTank(float left, float right) {
	robotDrive41->TankDrive(left, right);
	SmartDashboard::PutNumber("Front left",  frontLeftDrive->Get());
	SmartDashboard::PutNumber("Front right",  frontRightDrive->Get());
	SmartDashboard::PutNumber("Back left",  backLeftDrive->Get());
	SmartDashboard::PutNumber("Back right",  backRightDrive->Get());
}
