// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#define kUp true
#define kDown false

#include "DriveConveyor.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveConveyor::DriveConveyor(bool direction): Command() {
    m_direction = direction;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::conveyor.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveConveyor::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void DriveConveyor::Execute() {
	if (m_direction == kUp) {
		RobotMap::conveyorConveyorJag->Set(0.5);
	}

	else if (m_direction == kDown) {
		RobotMap::conveyorConveyorJag->Set(-0.5);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool DriveConveyor::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveConveyor::End() {
	Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveConveyor::Interrupted() {
	Stop();
}

void DriveConveyor::Stop() {
	RobotMap::conveyorConveyorJag->Set(0.0);
}
